import { auth } from "@clerk/nextjs/server";
import { getOrCreateWorkspace, getOutputs } from "@/lib/db";
import CopyBlock from "@/components/CopyBlock";

const TYPE_CONFIG: Record<string, { label: string; icon: string; color: string; description: string }> = {
  pulse: { 
    label: "Performance Pulse", 
    icon: "📊", 
    color: "border-l-twf-blue",
    description: "Daily heartbeat of your account performance."
  },
  budget: { 
    label: "Budget & Flighting", 
    icon: "💰", 
    color: "border-l-twf-orange",
    description: "Strategic spend recommendations and pacing."
  },
  client: { 
    label: "Client Update", 
    icon: "📧", 
    color: "border-l-twf-green",
    description: "Ready-to-send summary for your clients."
  },
  media_planner_optimizer: {
    label: "Media Planner & Optimizer",
    icon: "🎯",
    color: "border-l-indigo-600",
    description: "AI-powered strategic analysis and scaling roadmap (Gemini)."
  }
};

export default async function OutputsPage() {
  const { userId } = auth();
  const workspace = await getOrCreateWorkspace(userId!);
  const outputs = await getOutputs(workspace.id, workspace.retention_days);

  const today = new Date().toISOString().slice(0, 10);
  const todayOutputs = outputs.filter((o) => o.date === today);
  const history = outputs.filter((o) => o.date !== today);

  const grouped: Record<string, typeof history> = {};
  for (const o of history) {
    grouped[o.date] = grouped[o.date] ?? [];
    grouped[o.date].push(o);
  }

  return (
    <div className="max-w-5xl mx-auto pb-12">
      <header className="mb-10">
        <h1 className="text-3xl font-extrabold text-gray-900 dark:text-gray-100 tracking-tight">Jellopy Daily Briefing</h1>
        <p className="mt-2 text-lg text-gray-600 dark:text-gray-400 font-medium">
          Fresh insights generated by Jellopy, your AI media strategist.
        </p>
      </header>

      {/* Today's Section */}
      <section className="mb-12">
        <div className="flex items-center gap-3 mb-6">
          <div className="h-2 w-2 rounded-full bg-twf-green animate-pulse" />
          <h2 className="text-sm font-bold uppercase tracking-widest text-gray-500 dark:text-gray-500">Today&apos;s Intelligence · {today}</h2>
        </div>
        
        {todayOutputs.length === 0 ? (
          <div className="bg-white dark:bg-gray-800 border-2 border-dashed border-gray-200 dark:border-gray-700 rounded-2xl p-12 text-center">
            <div className="text-4xl mb-4">☕️</div>
            <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">Quiet morning...</h3>
            <p className="text-gray-500 dark:text-gray-400 mt-2 max-w-sm mx-auto">
              No reports generated yet for today. Head to the Overview to trigger a manual run.
            </p>
          </div>
        ) : (
          <div className="space-y-8">
            {todayOutputs.map((o) => (
              <OutputCard key={o.id} type={o.type} content={o.content_md} date={o.date} />
            ))}
          </div>
        )}
      </section>

      {/* Historical Reports */}
      {Object.keys(grouped).length > 0 && (
        <section>
          <h2 className="text-sm font-bold uppercase tracking-widest text-gray-500 dark:text-gray-500 mb-6">Past Briefings</h2>
          <div className="space-y-4">
            {Object.entries(grouped)
              .sort(([a], [b]) => b.localeCompare(a))
              .map(([date, items]) => (
                <details key={date} className="group bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-xl overflow-hidden transition-all hover:border-gray-300 dark:hover:border-gray-600">
                  <summary className="flex items-center justify-between p-5 cursor-pointer list-none">
                    <div className="flex items-center gap-4">
                      <span className="font-bold text-gray-900 dark:text-gray-100">{date}</span>
                      <span className="px-2.5 py-0.5 rounded-full bg-gray-100 dark:bg-gray-700 text-xs font-bold text-gray-600 dark:text-gray-400">
                        {items.length} Reports
                      </span>
                    </div>
                    <span className="text-gray-400 group-open:rotate-180 transition-transform">▼</span>
                  </summary>
                  <div className="p-5 pt-0 space-y-6 border-t border-gray-100 dark:border-gray-700">
                    {items.map((o) => (
                      <OutputCard key={o.id} type={o.type} content={o.content_md} date={o.date} compact />
                    ))}
                  </div>
                </details>
              ))}
          </div>
        </section>
      )}

      {workspace.plan === "free" && (
        <div className="mt-12 p-6 bg-blue-50 dark:bg-blue-950/30 rounded-xl border border-blue-100 dark:border-blue-900">
          <p className="text-sm text-blue-800 dark:text-blue-300 text-center">
            You&apos;re viewing the last <strong>{workspace.retention_days} days</strong> of history. 
            <button className="ml-2 font-bold underline hover:text-blue-600 dark:hover:text-blue-100">Upgrade to Pro</button> for unlimited access.
          </p>
        </div>
      )}
    </div>
  );
}

function OutputCard({ type, content, compact }: { type: string; content: string; date: string; compact?: boolean }) {
  const config = TYPE_CONFIG[type] || { label: type, icon: "📄", color: "border-l-gray-300", description: "" };

  return (
    <div className={`relative bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 rounded-2xl shadow-sm overflow-hidden border-l-4 ${config.color}`}>
      <div className="flex items-start justify-between p-6 pb-4 border-b border-gray-50 dark:border-gray-700/50">
        <div className="flex items-center gap-4">
          <span className="text-3xl">{config.icon}</span>
          <div>
            <h3 className="font-bold text-xl text-gray-900 dark:text-gray-100">{config.label}</h3>
            {!compact && <p className="text-sm text-gray-500 dark:text-gray-400 font-medium">{config.description}</p>}
          </div>
        </div>
        <CopyBlock content={content} />
      </div>
      
      <div className="p-6 overflow-x-auto">
        <div className="prose prose-sm dark:prose-invert max-w-none">
          {/* Simple Markdown-like renderer for human readability */}
          {content.split("\n").map((line, i) => {
            if (line.startsWith("# ")) return <h1 key={i} className="text-2xl font-black mb-4 text-gray-900 dark:text-white leading-tight">{line.replace("# ", "")}</h1>;
            if (line.startsWith("## ")) return <h2 key={i} className="text-lg font-bold mt-6 mb-3 text-gray-800 dark:text-gray-200 border-b border-gray-100 dark:border-gray-700 pb-1 uppercase tracking-tight">{line.replace("## ", "")}</h2>;
            if (line.startsWith("### ")) return <h3 key={i} className="text-md font-bold mt-4 mb-2 text-gray-700 dark:text-gray-300">{line.replace("### ", "")}</h3>;
            if (line.startsWith("- ")) return <div key={i} className="flex gap-3 mb-2 text-gray-700 dark:text-gray-300 leading-relaxed"><span className="text-twf-blue font-bold">·</span><span>{line.replace("- ", "").replace(/\*\*(.*?)\*\*/g, "$1")}</span></div>;
            if (line.trim() === "") return <div key={i} className="h-4" />;
            if (line.startsWith("|")) return null; // Simple skip for tables for now to avoid mess
            if (line.startsWith("---")) return <hr key={i} className="my-6 border-gray-100 dark:border-gray-700" />;
            
            // Handle bold text in regular lines (very basic)
            const processedLine = line.split(/(\*\*.*?\*\*)/).map((part, j) => {
              if (part.startsWith("**") && part.endsWith("**")) {
                return <strong key={j} className="text-gray-900 dark:text-white font-bold">{part.slice(2, -2)}</strong>;
              }
              return part;
            });

            return <p key={i} className="mb-3 text-gray-700 dark:text-gray-300 leading-relaxed font-medium">{processedLine}</p>;
          })}
        </div>
      </div>

      {type === "client" && (
        <div className="mx-6 mb-6 p-4 bg-twf-green/5 dark:bg-twf-green/10 border border-twf-green/20 rounded-xl flex items-center gap-3">
          <span className="text-lg">💡</span>
          <p className="text-xs text-twf-green-dark dark:text-twf-green font-semibold uppercase tracking-wider">
            Copy this and send to your client via Slack or Email.
          </p>
        </div>
      )}
    </div>
  );
}
