import { auth } from "@clerk/nextjs/server";
import { getOrCreateWorkspace, getOutputs } from "@/lib/db";
import CopyBlock from "@/components/CopyBlock";
import Link from "next/link";

const TYPE_CONFIG: Record<string, { label: string; icon: string; color: string; description: string; gradient: string }> = {
  pulse: { 
    label: "Performance Pulse", 
    icon: "📊", 
    color: "border-l-twf-blue",
    gradient: "from-blue-500/10 to-transparent",
    description: "Daily heartbeat of your account performance."
  },
  budget: { 
    label: "Budget & Flighting", 
    icon: "💰", 
    color: "border-l-twf-orange",
    gradient: "from-orange-500/10 to-transparent",
    description: "Strategic spend recommendations and pacing."
  },
  client: { 
    label: "Client Update", 
    icon: "📧", 
    color: "border-l-twf-green",
    gradient: "from-emerald-500/10 to-transparent",
    description: "Ready-to-send summary for your clients."
  },
  media_planner_optimizer: {
    label: "Media Planner & Optimizer",
    icon: "🎯",
    color: "border-l-indigo-600",
    gradient: "from-indigo-600/10 to-transparent",
    description: "AI-powered strategic analysis and scaling roadmap (Gemini)."
  }
};

export default async function OutputsPage({ searchParams }: { searchParams: { type?: string } }) {
  const { userId } = auth();
  const workspace = await getOrCreateWorkspace(userId!);
  const outputs = await getOutputs(workspace.id, workspace.retention_days);

  const activeFilter = searchParams.type;
  const filteredOutputs = activeFilter ? outputs.filter(o => o.type === activeFilter) : outputs;

  // Group by minute-level timestamp to catch reports from the same run
  const grouped: Record<string, typeof filteredOutputs> = {};
  for (const o of filteredOutputs) {
    const dt = new Date(o.created_at);
    // Key format: "2026-03-18 13:45"
    const key = dt.toISOString().slice(0, 16).replace('T', ' ');
    grouped[key] = grouped[key] ?? [];
    grouped[key].push(o);
  }

  const sortedKeys = Object.keys(grouped).sort((a, b) => b.localeCompare(a));
  const today = new Date().toISOString().slice(0, 10);

  return (
    <div className="max-w-5xl mx-auto pb-24">
      <header className="mb-12">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div>
            <nav className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-500 mb-4">
              <Link href="/" className="hover:text-indigo-400 transition-colors">Workspace</Link>
              <span>/</span>
              <span className="text-slate-300">Briefings</span>
            </nav>
            <h1 className="text-4xl font-black text-white tracking-tight mb-3">Jellopy Daily Briefing</h1>
            <p className="text-lg text-slate-400 font-medium max-w-2xl leading-relaxed">
              Fresh insights generated by your AI media strategist. Precision-tuned analysis for your Google Ads account.
            </p>
          </div>
        </div>

        {/* Quick Filters */}
        <div className="mt-10 flex flex-wrap gap-2">
          <Link 
            href="/outputs"
            className={`px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider border transition-all ${!activeFilter ? "bg-indigo-600 border-indigo-500 text-white shadow-lg shadow-indigo-500/20" : "bg-slate-900/50 border-slate-800 text-slate-400 hover:border-slate-700"}`}
          >
            All Reports
          </Link>
          {Object.entries(TYPE_CONFIG).map(([key, cfg]) => (
            <Link 
              key={key}
              href={`/outputs?type=${key}`}
              className={`px-4 py-2 rounded-xl text-xs font-bold uppercase tracking-wider border transition-all ${activeFilter === key ? "bg-indigo-600 border-indigo-500 text-white shadow-lg shadow-indigo-500/20" : "bg-slate-900/50 border-slate-800 text-slate-400 hover:border-slate-700"}`}
            >
              {cfg.icon} {cfg.label}
            </Link>
          ))}
        </div>
      </header>

      {/* Unified Timeline Section */}
      <section className="mb-16">
        <div className="flex items-center gap-4 mb-8">
          <div className="h-px flex-1 bg-gradient-to-r from-transparent via-slate-800 to-transparent" />
          <div className="flex items-center gap-3 px-6 py-2 bg-slate-900/80 border border-slate-800 rounded-full shadow-inner">
            <h2 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 text-center">Intelligence Stream</h2>
          </div>
          <div className="h-px flex-1 bg-gradient-to-r from-transparent via-slate-800 to-transparent" />
        </div>
        
        {sortedKeys.length === 0 ? (
          <div className="bg-slate-900/30 border-2 border-dashed border-slate-800 rounded-3xl p-16 text-center backdrop-blur-sm">
            <div className="w-20 h-20 bg-slate-800/50 rounded-2xl flex items-center justify-center text-4xl mx-auto mb-6 shadow-inner">☕️</div>
            <h3 className="text-xl font-bold text-white mb-2">No intelligence found.</h3>
            <p className="text-slate-400 max-w-sm mx-auto leading-relaxed">
              We couldn&apos;t find any briefings {activeFilter ? "for this category" : "yet"}. Head to the Overview to trigger a manual sync.
            </p>
            {!activeFilter && (
              <Link href="/">
                <button className="mt-8 btn-secondary">Go to Overview</button>
              </Link>
            )}
          </div>
        ) : (
          <div className="space-y-6">
            {sortedKeys.map((key, index) => {
              const items = grouped[key];
              const dt = new Date(key);
              const isToday = key.startsWith(today);
              const displayDate = dt.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' });
              const displayTime = dt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

              return (
                <details 
                  key={key} 
                  open={index === 0}
                  className="group bg-slate-900/20 border border-slate-800/50 rounded-3xl overflow-hidden transition-all hover:bg-slate-900/40 hover:border-slate-700"
                >
                  <summary className="flex items-center justify-between p-6 md:p-8 cursor-pointer list-none select-none">
                    <div className="flex items-center gap-6 md:gap-10">
                      <div className="flex flex-col">
                        <div className="flex items-center gap-2 mb-1">
                          <span className="text-[10px] font-black uppercase tracking-widest text-slate-500">Execution Run</span>
                          {isToday && <span className="w-1.5 h-1.5 rounded-full bg-twf-green animate-pulse shadow-[0_0_8px_rgba(0,208,132,0.5)]" />}
                        </div>
                        <div className="flex items-baseline gap-2">
                          <span className="font-black text-slate-100 text-xl tracking-tight">{displayDate}</span>
                          <span className="font-bold text-indigo-400 text-sm">{displayTime}</span>
                        </div>
                      </div>
                      
                      <div className="hidden sm:block h-10 w-px bg-slate-800" />
                      
                      <div className="flex items-center gap-4">
                        <div className="flex -space-x-2">
                          {items.map((it, idx) => (
                            <div key={idx} className="w-10 h-10 rounded-xl bg-slate-800 border-2 border-slate-950 flex items-center justify-center text-lg shadow-xl" title={TYPE_CONFIG[it.type]?.label}>
                              {TYPE_CONFIG[it.type]?.icon || "📄"}
                            </div>
                          ))}
                        </div>
                        <span className="hidden md:inline-block text-[10px] font-black uppercase tracking-widest text-slate-500 bg-slate-800/50 px-3 py-1.5 rounded-lg border border-slate-700/50">
                          {items.length} Intelligence Modules
                        </span>
                      </div>
                    </div>
                    
                    <div className="flex items-center gap-4">
                       <div className="w-10 h-10 rounded-xl bg-slate-800/50 border border-slate-700/50 flex items-center justify-center text-slate-500 group-open:rotate-180 transition-all group-hover:bg-slate-700 group-hover:text-slate-300 shadow-inner">
                        ▼
                      </div>
                    </div>
                  </summary>
                  
                  <div className="px-6 pb-10 md:px-10 md:pb-12 space-y-12 border-t border-slate-800/50 bg-slate-950/40">
                    <div className="pt-10 grid grid-cols-1 gap-12">
                      {items.map((o) => (
                        <OutputCard key={o.id} type={o.type} content={o.content_md} date={o.date} />
                      ))}
                    </div>
                  </div>
                </details>
              );
            })}
          </div>
        )}
      </section>

      {workspace.plan === "free" && (
        <div className="mt-16 p-8 bg-indigo-500/5 border border-indigo-500/20 rounded-3xl text-center">
          <p className="text-slate-400">
            You&apos;re currently on the <strong className="text-indigo-400">Free Tier</strong> with <strong>{workspace.retention_days} days</strong> of history. 
          </p>
          <Link href="/settings">
            <button className="mt-4 font-black text-xs uppercase tracking-widest text-indigo-400 hover:text-indigo-300 transition-colors underline decoration-2 underline-offset-4">
              Unlock Unlimited Archiving
            </button>
          </Link>
        </div>
      )}

      {/* Strategy CTA */}
      <section className="mt-24 text-center">
        <div className="relative inline-block p-px rounded-3xl bg-gradient-to-b from-slate-700 to-slate-900 shadow-2xl overflow-hidden group">
          <div className="absolute inset-0 bg-gradient-to-r from-indigo-500/20 via-purple-500/20 to-pink-500/20 opacity-0 group-hover:opacity-100 transition-opacity" />
          <div className="relative bg-slate-950 rounded-[23px] px-12 py-10 max-w-2xl border border-white/5">
            <div className="text-4xl mb-6">🔮</div>
            <h3 className="text-3xl font-black text-white mb-4 tracking-tight">Turn these insights into profit.</h3>
            <p className="text-slate-400 mb-8 text-lg font-medium leading-relaxed">
              Jellopy has synthesized this data into specific, approved campaign adjustments waiting for your implementation.
            </p>
            <Link href="/recommendations">
              <button className="btn-primary px-10 py-4 text-base tracking-tight">
                Review Execution Strategy
              </button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}

function OutputCard({ type, content, compact }: { type: string; content: string; date: string; compact?: boolean }) {
  const config = TYPE_CONFIG[type] || { label: type, icon: "📄", color: "border-l-slate-700", gradient: "from-slate-500/5 to-transparent", description: "" };

  return (
    <div className={`group relative bg-slate-900/40 border border-slate-800 rounded-3xl shadow-xl overflow-hidden border-l-4 ${config.color} transition-all hover:border-slate-700 hover:bg-slate-900/60`}>
      <div className={`absolute top-0 left-0 w-64 h-64 bg-gradient-to-br ${config.gradient} opacity-50 pointer-events-none transition-opacity group-hover:opacity-80`} />
      
      <div className="relative flex flex-col md:flex-row md:items-center justify-between p-8 pb-6 gap-6 border-b border-slate-800/50">
        <div className="flex items-center gap-5">
          <div className="w-16 h-16 rounded-2xl bg-slate-800/50 flex items-center justify-center text-4xl shadow-inner group-hover:scale-105 transition-transform">
            {config.icon}
          </div>
          <div>
            <div className="flex items-center gap-3 mb-1">
              <h3 className="font-black text-2xl text-white tracking-tight">{config.label}</h3>
              {compact && <span className="text-[10px] font-black uppercase tracking-widest px-2 py-0.5 rounded bg-slate-800 text-slate-500">Archive</span>}
            </div>
            {!compact && <p className="text-slate-400 font-medium leading-relaxed max-w-md">{config.description}</p>}
          </div>
        </div>
        <div className="flex items-center gap-3 self-end md:self-center">
           <CopyBlock content={content} />
        </div>
      </div>
      
      <div className="relative p-8 pt-6 overflow-x-auto">
        <div className="prose prose-invert max-w-none prose-headings:tracking-tight prose-headings:font-black prose-p:text-slate-300 prose-p:leading-relaxed prose-li:text-slate-300 prose-strong:text-white">
          {content.split("\n").map((line, i) => {
            if (line.startsWith("# ")) return <h1 key={i} className="text-3xl mb-6 text-white">{line.replace("# ", "")}</h1>;
            if (line.startsWith("## ")) return <h2 key={i} className="text-xl mt-10 mb-4 text-slate-100 border-b border-slate-800 pb-2 flex items-center gap-3"><span className="w-1.5 h-6 bg-indigo-500 rounded-full" />{line.replace("## ", "")}</h2>;
            if (line.startsWith("### ")) return <h3 key={i} className="text-lg mt-8 mb-3 text-slate-200">{line.replace("### ", "")}</h3>;
            if (line.startsWith("- ")) return <div key={i} className="flex gap-4 mb-3 text-slate-300 items-start"><span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-500 flex-shrink-0" /><span>{line.replace("- ", "").replace(/\*\*(.*?)\*\*/g, "$1")}</span></div>;
            if (line.trim() === "") return <div key={i} className="h-4" />;
            if (line.startsWith("|")) return null; // Simple skip for tables for now
            if (line.startsWith("---")) return <hr key={i} className="my-10 border-slate-800" />;
            
            const processedLine = line.split(/(\*\*.*?\*\*)/).map((part, j) => {
              if (part.startsWith("**") && part.endsWith("**")) {
                return <strong key={j} className="text-white font-bold">{part.slice(2, -2)}</strong>;
              }
              return part;
            });

            return <p key={i} className="mb-4 text-slate-300 font-medium leading-relaxed">{processedLine}</p>;
          })}
        </div>
      </div>

      {type === "media_planner_optimizer" && (
        <div className="relative mx-8 mb-8 p-1 rounded-2xl bg-gradient-to-r from-indigo-500 to-purple-500 shadow-lg shadow-indigo-500/10">
          <div className="bg-slate-900 rounded-[15px] p-6 flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-full bg-indigo-500/10 flex items-center justify-center text-2xl">⚡️</div>
              <div>
                <p className="font-black text-white tracking-tight">Actionable Strategy Primed</p>
                <p className="text-sm text-slate-400 font-medium">Ready to deploy these insights to your campaigns.</p>
              </div>
            </div>
            <Link href="/recommendations">
              <button className="w-full md:w-auto bg-white text-slate-950 px-8 py-2.5 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-slate-200 transition-colors shadow-xl">
                View Recommendations
              </button>
            </Link>
          </div>
        </div>
      )}

      {type === "client" && (
        <div className="relative mx-8 mb-8 p-6 bg-emerald-500/5 border border-emerald-500/20 rounded-2xl flex items-center gap-4 group/tip">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center text-xl group-hover/tip:scale-110 transition-transform">💡</div>
          <p className="text-xs text-emerald-400 font-black uppercase tracking-[0.15em] leading-relaxed">
            PRO-TIP: This summary is calibrated for client consumption. Copy and send via Slack or Email to keep stakeholders aligned.
          </p>
        </div>
      )}
    </div>
  );
}
